name: Compile Monthly ZINE

on:
  schedule:
    - cron: "0 0 28 * *"  # JST 9:00（UTC 0:00）に毎月28日実行
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run ZINE compiler
        run: python compile_zine.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/zine/
          git commit -m "add: compiled ZINE for $(date +'%Y-%m')" || echo "No changes to commit"
          git push
