name: Format Weekly Note

on:
  schedule:
    - cron: "0 0 * * 0"  # 毎週日曜 UTC 0:00 = 月曜朝 JST 9:00
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run note formatter
        run: python format_note.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f output/note/note_post.md ]; then
            git add output/note/note_post.md
            git commit -m "add: weekly note post $(date +'%Y-%m-%d')" || echo "No changes to commit"
            git push
          else
            echo "No note_post.md found. Skipping commit."
          fi
