name: Generate Daily Kuyou Poem

on:
  schedule:
    - cron: "59 14 * * *"  # JST 23:59（UTC換算）
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run poem generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Debug output (optional)
        run: |
          echo "Listing output/logs/"
          ls -la output/logs || echo "No output/logs directory found"

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/logs/*.md
          git commit -m "add: auto-generated kuyou poem for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
