name: Generate Daily Kuyou Poem

on:
  schedule:
    - cron: "59 14 * * *"  # JST 23:59（UTC換算）
  workflow_dispatch:

jobs:
  generate_and_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai

      - name: Generate Kuyou Poem
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_kuyou_poem.py  # output/poems/ に .md を生成

      - name: Commit and push generated poem
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f output/poems/*.md output/logs/*.json output/logs/*.md || echo "No files to commit"
          git commit -m "add: auto-generated kuyou poem for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: Generate and Post via Poemkun Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: python generate_post_from_repo.py poem-cemetery daily-kuyou
